package ui

// helpContent is the static text shown in the :help buffer.
var helpContent = []string{
	"CHAT LIST  Normal mode",
	"",
	"  j / k         move cursor down / up",
	"  H / L         top / bottom of viewport",
	"  g             first chat",
	"  G             last chat",
	"  enter         open chat",
	"",
	"CHAT  Normal mode — navigation",
	"",
	"  j / k         move cursor down / up",
	"  H / L         top / bottom of viewport",
	"  ctrl+u        half page up",
	"  ctrl+d        half page down",
	"  g             oldest message",
	"  G             newest message",
	"  m{a-z}        set mark",
	"  '{a-z}        jump to mark",
	"",
	"CHAT  Normal mode — messages",
	"",
	"  r             reply to message under cursor",
	"  e             edit message under cursor",
	"  f             forward message under cursor",
	"  dd / dm       delete for me",
	"  da            delete for everyone",
	"  yy            yank message text to register",
	"  p             paste from register into input",
	"",
	"CHAT  Visual mode  (enter with v)",
	"",
	"  j / k         extend selection down / up",
	"  H / L         extend to top / bottom of viewport",
	"  g / G         extend to oldest / newest message",
	"  y             yank all selected messages",
	"  r             reply to last selected message",
	"  f             forward all selected messages",
	"  dd / dm       delete selected (for me)",
	"  da            delete selected (for everyone)",
	"  esc           exit Visual mode",
	"",
	"MODES",
	"",
	"  a / i         enter Insert mode",
	"  esc           back to Normal mode",
	"  :             enter Command mode",
	"  v             enter Visual mode",
	"",
	"WINDOWS",
	"",
	"  ctrl+w h      focus left window",
	"  ctrl+w l      focus right window",
	"  ctrl+w w      cycle focus",
	"",
	"COMMANDS",
	"",
	"  :q            close window (quit if last)",
	"  :q!           force quit",
	"  :wq / :qa     force quit",
	"  :vs [arg]     vertical split (arg: buffer id or chats)",
	"  :close        close focused window",
	"  :set showarchive     show archived chats",
	"  :set noshowarchive   hide archived chats (default)",
	"  :help         this help",
	"",
	"BUFFERS",
	"",
	"  :ls           list buffers",
	"  :b N          switch to buffer N",
	"  :b#           alternate buffer",
	"  :bn           next buffer",
	"  :bp           previous buffer",
	"  :bd [N]       delete buffer",
	"  :chats        go to chat list",
}
