package ui

// helpContent is the static text shown in the :help buffer.
var helpContent = []string{
	"NAVIGATION  chat list",
	"",
	"  j / k         move cursor down / up",
	"  g             first chat",
	"  G             last chat",
	"  enter         open chat",
	"",
	"NAVIGATION  chat",
	"",
	"  j / k         move cursor down / up",
	"  h / l         move cursor left / right",
	"  ctrl+u        half page up",
	"  ctrl+d        half page down",
	"  g             oldest message",
	"  G             newest message",
	"",
	"MODES",
	"",
	"  a / i         enter Insert mode",
	"  esc           back to Normal mode",
	"  :             enter Command mode",
	"  v             enter Visual mode",
	"",
	"MESSAGES",
	"",
	"  r             reply to message under cursor",
	"  e             edit message under cursor",
	"  dd / dm       delete for me",
	"  da            delete for everyone",
	"  yy            yank message text to register",
	"  p             paste from register into input",
	"",
	"WINDOWS",
	"",
	"  ctrl+w h      focus left window",
	"  ctrl+w l      focus right window",
	"  ctrl+w w      cycle focus",
	"",
	"COMMANDS",
	"",
	"  :q            close window (quit if last)",
	"  :q!           force quit",
	"  :wq / :qa     force quit",
	"  :vs [arg]     vertical split (arg: buffer id or chats)",
	"  :close        close focused window",
	"  :set showarchive     show archived chats",
	"  :set noshowarchive   hide archived chats (default)",
	"  :help         this help",
	"",
	"BUFFERS",
	"",
	"  :ls           list buffers",
	"  :b N          switch to buffer N",
	"  :b#           alternate buffer",
	"  :bn           next buffer",
	"  :bp           previous buffer",
	"  :bd [N]       delete buffer",
	"  :chats        go to chat list",
}
